### ISSUE TITLE
[core] Support more cooldown message options

### ISSUE THREAD

**Issue by itsHobbes** [BoscoJared/disparse#26]
Currently `sendCooldownMessage` accepts a boolean type. [See docs](https://disparse.readthedocs.io/en/latest/deep_dive/cooldown/#cooldown)

This feature request proposes creating an Enum to extend functionality. 
`disabled` - cooldown message is not sent
`reaction` - invocation command receives a reaction with "🕒" indicating the command is on cooldown.
`enabled` - cooldown message is sent.

Currently checking of the `sendCooldownMessage` field is done [here](https://github.com/BoscoJared/disparse/blob/master/disparse-core/src/main/java/disparse/parser/dispatch/CommandRegistrar.java#L307-L309)

**Comment by BoscoJared** [comment]
This feature sounds good to me, and definitely would be useful.  Waiting for a little to see if anyone is interested in contributing as this doesn't require much deep changes in the codebase.  Anyone interested in taking on this issue should reach out on Discord to me Bosco#8564 for more context and help.

**Comment by dy-eraser** [comment]
Hi There,

I can help you guys on this since it is a small effort. In fact I already made the changed!

Regards,
Daniel

**Comment by BoscoJared** [comment]
@dy-eraser Awesome, feel free to make a PR and I'll review it!

**Comment by dy-eraser** [comment]
@BoscoJared, pls review my changes and let me know.

**Comment by BoscoJared** [comment]
closed by #31
