### ISSUE TITLE
[core] Auto-generate commands.md file detailing command information

### ISSUE THREAD

**Issue by itsHobbes** [BoscoJared/disparse#29]
This issue proposes to add an optional step in the [Dispatch.Builder](https://github.com/BoscoJared/disparse/blob/master/disparse-core/src/main/java/disparse/discord/AbstractDispatcher.java) to auto generate a `commands.md` file in the root directory.

The default for this option should be false.

The file structure should look like this
Template:
```
# Commands

## Command Name

Command Description

* **Cooldown:** Command cooldown

* **Required Permission:** Permissions if specified

* **Required Role:** Role if specified

#### Arguments

* `shortname`, `longname` : argument description

#### Usage

`example usage from usage annotation`
```
Example:
```
# Commands

## mute

This command will mute the target user

* **Cooldown:** 5 seconds per User

* **Required Permission:** Ban

* **Required Role:** Moderator

#### Arguments

* `-u`, `--user` : The target userid to mute

#### Usage

`!mute -u 0123456789`
```

If any information is not provided (permissions, roles, cooldown, they can be marked as `N/A`)

**Comment by BoscoJared** [comment]
closed by #30
